{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0-feat-just-the-clothes-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-just-the-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-just-the-clothes-dev+mc.1.20.1.jar",
          "size": 332297,
          "sha512": "5fc9d6018c65288ab089e3463383abba225df40c6c477c45d3823d675045864af27c24d3d8351bf5f1c9a806df4e17ea8138c5fbb0507fee89300c131611365f",
          "sha256": "59665646536a3bae11c436d91edf5b1c11348bfde0b70fbdec6ecefe6254a908",
          "sha1": "b80015cd3cdc063fe8438fb5916345fb9b628cba",
          "md5": "98abf8172033b08f4238f2ea88ec5c6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-just-the-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-just-the-clothes-dev+mc.1.20.1.jar",
          "size": 332297,
          "sha512": "5fc9d6018c65288ab089e3463383abba225df40c6c477c45d3823d675045864af27c24d3d8351bf5f1c9a806df4e17ea8138c5fbb0507fee89300c131611365f",
          "sha256": "59665646536a3bae11c436d91edf5b1c11348bfde0b70fbdec6ecefe6254a908",
          "sha1": "b80015cd3cdc063fe8438fb5916345fb9b628cba",
          "md5": "98abf8172033b08f4238f2ea88ec5c6a"
        }
      ]
    }
  ]
}
