{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "size": 13250589,
          "sha512": "ab9937848d820db869154b0a393c880c9714a29a147710165385e9654549a05300c9a0b6573bdc4fa11b7f4cacc718cb9ca58bd99097d9cd1052447d19f286df",
          "sha256": "621cf44e0f5673874e32c39092d209dc3649ca2a080e1bdcba1873a9897e14e7",
          "sha1": "d6dbccd109f337c696a22ab27c05facaa564e308",
          "md5": "c6b533dc90c68cbafb9135df814b9488"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.amble",
          "module": "ait",
          "version": {
            "requires": "1.2.13-dev+mc.1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "size": 13250589,
          "sha512": "ab9937848d820db869154b0a393c880c9714a29a147710165385e9654549a05300c9a0b6573bdc4fa11b7f4cacc718cb9ca58bd99097d9cd1052447d19f286df",
          "sha256": "621cf44e0f5673874e32c39092d209dc3649ca2a080e1bdcba1873a9897e14e7",
          "sha1": "d6dbccd109f337c696a22ab27c05facaa564e308",
          "md5": "c6b533dc90c68cbafb9135df814b9488"
        }
      ]
    }
  ]
}
