{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "size": 13243350,
          "sha512": "5188a4b73246fb2321ee857f8b81a4041bd69d7c4b3b15a023cefa9985ed0d117fc4ba57664b5d986fb223164c1b39bc180b096786307dc3bd5b730d2e25b2dd",
          "sha256": "61bf246a4c8c24adcd41bc6fe1c2db05529361bb721868172dd4af84ff797bd6",
          "sha1": "2c25bf4a521471dda09f0d00b943124eb1d9bb61",
          "md5": "7138a7782220199a25b7506e312b8a9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.amble",
          "module": "ait",
          "version": {
            "requires": "1.2.13-dev+mc.1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "size": 13243350,
          "sha512": "5188a4b73246fb2321ee857f8b81a4041bd69d7c4b3b15a023cefa9985ed0d117fc4ba57664b5d986fb223164c1b39bc180b096786307dc3bd5b730d2e25b2dd",
          "sha256": "61bf246a4c8c24adcd41bc6fe1c2db05529361bb721868172dd4af84ff797bd6",
          "sha1": "2c25bf4a521471dda09f0d00b943124eb1d9bb61",
          "md5": "7138a7782220199a25b7506e312b8a9b"
        }
      ]
    }
  ]
}
