{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "size": 13234495,
          "sha512": "17c0510551b4be12f18411ae8798d6bdccc863628ae1c0f26ee7e1723468d4fd1d48585b48cce2fbc6d5797a6ec21d59df29de66377d31d56008cbd5f7bf7b07",
          "sha256": "70aad55e91ecaacadbb4511fc167feacde9ba66c5c9b8c464d4f2b2df7a79a8a",
          "sha1": "bc51b79d22c61518efa845e18128256d38d6bf9e",
          "md5": "9bac6a1b4bb1466df7fe950d5a081d8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.amble",
          "module": "ait",
          "version": {
            "requires": "1.2.13-dev+mc.1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-dev+mc.1.20.1.jar",
          "size": 13234495,
          "sha512": "17c0510551b4be12f18411ae8798d6bdccc863628ae1c0f26ee7e1723468d4fd1d48585b48cce2fbc6d5797a6ec21d59df29de66377d31d56008cbd5f7bf7b07",
          "sha256": "70aad55e91ecaacadbb4511fc167feacde9ba66c5c9b8c464d4f2b2df7a79a8a",
          "sha1": "bc51b79d22c61518efa845e18128256d38d6bf9e",
          "md5": "9bac6a1b4bb1466df7fe950d5a081d8f"
        }
      ]
    }
  ]
}
