{
  "formatVersion": "1.1",
  "component": {
    "group": "com.addie",
    "module": "stargate-network",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "stargate-network-1.0.0.jar",
          "url": "stargate-network-1.0.0.jar",
          "size": 308404,
          "sha512": "22ae21fccd45fe6fa0dd23cda8896d336eaf3e4b88edb9310017b06e639c72f57608363edaffc7f9285ba167e1debee7fbd2fae28225aca1c7b0bb9721129f5f",
          "sha256": "636603c4ff5cc52c20cce2fae096e49958368f084d90dc3428f36828586953fd",
          "sha1": "3a9c7be96fcef990479b5ef7a9e1f8291c66dbef",
          "md5": "64ab05c27b92d2466ff7278f4cfe7eca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.7+1.20.1"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.amble",
          "module": "stargate",
          "version": {
            "requires": "0.0.0-dev+mc.1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-network-1.0.0.jar",
          "url": "stargate-network-1.0.0.jar",
          "size": 308404,
          "sha512": "22ae21fccd45fe6fa0dd23cda8896d336eaf3e4b88edb9310017b06e639c72f57608363edaffc7f9285ba167e1debee7fbd2fae28225aca1c7b0bb9721129f5f",
          "sha256": "636603c4ff5cc52c20cce2fae096e49958368f084d90dc3428f36828586953fd",
          "sha1": "3a9c7be96fcef990479b5ef7a9e1f8291c66dbef",
          "md5": "64ab05c27b92d2466ff7278f4cfe7eca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-network-1.0.0-sources.jar",
          "url": "stargate-network-1.0.0-sources.jar",
          "size": 294160,
          "sha512": "c225cba51c975d3fad56280548d4706f2f909208d79e58c8bc0261cdd5b8c7eff515957df97e413cca9a0c934e624b24d0c3ee1c2e1e9addb46894c9eae36b8a",
          "sha256": "bdebb90e70804756f29c535e4a37f54bdfcc30fc471875d9e1a81bf9047d4013",
          "sha1": "a2a09931cf362d1196dc16f84ead4bf32fc193c2",
          "md5": "89263ecdfc6988e04d9521d50dde69c6"
        }
      ]
    }
  ]
}
