{
  "formatVersion": "1.1",
  "component": {
    "group": "com.addie",
    "module": "stargate-network",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "stargate-network-1.0.0.jar",
          "url": "stargate-network-1.0.0.jar",
          "size": 257851,
          "sha512": "4da3454859db151dfcff41cf2ff675942166e0e7957f10a6a2b761847410d7f1c75b24ca72fe454cb46255c749b6a8d1b16df6a5605ef36784a35fd3b6f5274a",
          "sha256": "730f71bc97260516d0fb7178b4dfe442d8066c99970c12fdd02c4ad08dfc0a34",
          "sha1": "9ae3baed24bc99525f0c2c1225c650c420f957db",
          "md5": "3a62b04311b1deb99e8d466c2d1b8913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "dev.amble",
          "module": "stargate",
          "version": {
            "requires": "0.0.0-dev+mc.1.20.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-network-1.0.0.jar",
          "url": "stargate-network-1.0.0.jar",
          "size": 257851,
          "sha512": "4da3454859db151dfcff41cf2ff675942166e0e7957f10a6a2b761847410d7f1c75b24ca72fe454cb46255c749b6a8d1b16df6a5605ef36784a35fd3b6f5274a",
          "sha256": "730f71bc97260516d0fb7178b4dfe442d8066c99970c12fdd02c4ad08dfc0a34",
          "sha1": "9ae3baed24bc99525f0c2c1225c650c420f957db",
          "md5": "3a62b04311b1deb99e8d466c2d1b8913"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-network-1.0.0-sources.jar",
          "url": "stargate-network-1.0.0-sources.jar",
          "size": 215260,
          "sha512": "a1d7f9b1f58b3c29c7873084a741d34b5e97b9aae67dfbf13e44098e5bdaa8c37097f28893ec7b3ed597d4c0c594e1636f24cf2383ad7e07de05be90422d0bbe",
          "sha256": "f34e9ca4a5f3cbdb4c04c65784cb31f710bf257fd28a27c15d1a6f7e4577121a",
          "sha1": "70db44075b79486f8ba25fa071daedfbcb110f4f",
          "md5": "b7fcd624331eb1cfaf9b23d6e9b07dc9"
        }
      ]
    }
  ]
}
