{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0.5-1.20.1-beta-feat-clothes",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ait-extras-1.1.0.5-1.20.1-beta-feat-clothes.jar",
          "url": "ait-extras-1.1.0.5-1.20.1-beta-feat-clothes.jar",
          "size": 12815232,
          "sha512": "d810ec0b36f5267d536ddef28768050825e21e646865c58d8f0f103c6a657c5735676e8402738fab797b40ada44e7c80caefe28882bc6555c1b75acc063b0a59",
          "sha256": "31b2b0de17c11af3e87360afffe8b314c77c885c9073b83bde10b6b0ff5f1474",
          "sha1": "2a19f795a3da48d6eb0307b5d97e6205ffaa17b8",
          "md5": "bdad400232119cae83e2b074af0e6b90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.amble",
          "module": "ait",
          "version": {
            "requires": "1.2.13-build.1896+mc.1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0.5-1.20.1-beta-feat-clothes.jar",
          "url": "ait-extras-1.1.0.5-1.20.1-beta-feat-clothes.jar",
          "size": 12815232,
          "sha512": "d810ec0b36f5267d536ddef28768050825e21e646865c58d8f0f103c6a657c5735676e8402738fab797b40ada44e7c80caefe28882bc6555c1b75acc063b0a59",
          "sha256": "31b2b0de17c11af3e87360afffe8b314c77c885c9073b83bde10b6b0ff5f1474",
          "sha1": "2a19f795a3da48d6eb0307b5d97e6205ffaa17b8",
          "md5": "bdad400232119cae83e2b074af0e6b90"
        }
      ]
    }
  ]
}
