{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0-feat-clothes-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "size": 12826282,
          "sha512": "ac90e4d4318351c3d3a735de0e1abfad9455608c938e6d38f9e149b985ffbedabbc8e5cb011d16f587641668099011a16edf77e5e3159929ee3817561e958daa",
          "sha256": "2b4929767916bd4e0bffa46a2dcab5003d79185861cdc22c402c50ce89de998e",
          "sha1": "b7b05e02afc3b866ec31ffc114da74bb94b56b27",
          "md5": "78142cd52ac9410afe93239107722870"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.amble",
          "module": "ait",
          "version": {
            "requires": "1.2.13-dev+mc.1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "size": 12826282,
          "sha512": "ac90e4d4318351c3d3a735de0e1abfad9455608c938e6d38f9e149b985ffbedabbc8e5cb011d16f587641668099011a16edf77e5e3159929ee3817561e958daa",
          "sha256": "2b4929767916bd4e0bffa46a2dcab5003d79185861cdc22c402c50ce89de998e",
          "sha1": "b7b05e02afc3b866ec31ffc114da74bb94b56b27",
          "md5": "78142cd52ac9410afe93239107722870"
        }
      ]
    }
  ]
}
