{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0-feat-clothes-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "size": 12859466,
          "sha512": "bb69a09a172908598d9beb6e5031d0f9aa14cad2f4bcaf5e3a870c17c1e518251b3c25451a80db598d3b2fd96ec5c8cd057d83421b8f77c182d6bbb37e20c757",
          "sha256": "da757fd3345c6255a0c87b18621cf6637fec2eb141cc9823418b9529c4287895",
          "sha1": "3474bcbba41f930e41ef20005c3222b352d1ac43",
          "md5": "b4c5d9050762dad99fd13d59ad4337b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.amble",
          "module": "ait",
          "version": {
            "requires": "1.2.13-dev+mc.1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "size": 12859466,
          "sha512": "bb69a09a172908598d9beb6e5031d0f9aa14cad2f4bcaf5e3a870c17c1e518251b3c25451a80db598d3b2fd96ec5c8cd057d83421b8f77c182d6bbb37e20c757",
          "sha256": "da757fd3345c6255a0c87b18621cf6637fec2eb141cc9823418b9529c4287895",
          "sha1": "3474bcbba41f930e41ef20005c3222b352d1ac43",
          "md5": "b4c5d9050762dad99fd13d59ad4337b9"
        }
      ]
    }
  ]
}
