{
  "formatVersion": "1.1",
  "component": {
    "group": "com",
    "module": "ait-extras",
    "version": "1.1.0-feat-clothes-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "size": 12826318,
          "sha512": "7c78da1618760af1daf01ad7eab7c0f07f80602ba8aa5a47c083f3b1a2aceb377bef2c0ce1950ffc8a7e15b949cbb5d5215e6d77b5a4c547ebc320947d186fff",
          "sha256": "2dc3f2f40e3edce40c2d2cf0364f938d4d67c0ac8f8c8a76c51c3b16138ab055",
          "sha1": "d7ec8f29f4398f398e93db74f9dda7b096d2ff2a",
          "md5": "1d2a09016448ae6686888327472769d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.amble",
          "module": "ait",
          "version": {
            "requires": "1.2.13-dev+mc.1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "url": "ait-extras-1.1.0-feat-clothes-dev+mc.1.20.1.jar",
          "size": 12826318,
          "sha512": "7c78da1618760af1daf01ad7eab7c0f07f80602ba8aa5a47c083f3b1a2aceb377bef2c0ce1950ffc8a7e15b949cbb5d5215e6d77b5a4c547ebc320947d186fff",
          "sha256": "2dc3f2f40e3edce40c2d2cf0364f938d4d67c0ac8f8c8a76c51c3b16138ab055",
          "sha1": "d7ec8f29f4398f398e93db74f9dda7b096d2ff2a",
          "md5": "1d2a09016448ae6686888327472769d1"
        }
      ]
    }
  ]
}
