{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lib",
    "module": "callisto",
    "version": "1.0.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "url": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "size": 112553,
          "sha512": "887240e754eb2e1c982bbc4b2952f2b803e65fdc1a46b6624b467b0c4719ab51be05f945f15525f80cc99297bebc0ed5d4aee2f1606f012082d326bd81d8a978",
          "sha256": "bd67579fc302704016445b9dce507b928d004f537efa6445e18ea6e18b679411",
          "sha1": "85f02d36e45c41f3607436ce556c77f7e02b2088",
          "md5": "479da45ba8ae4d32050ff8674bcc826d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "url": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "size": 112553,
          "sha512": "887240e754eb2e1c982bbc4b2952f2b803e65fdc1a46b6624b467b0c4719ab51be05f945f15525f80cc99297bebc0ed5d4aee2f1606f012082d326bd81d8a978",
          "sha256": "bd67579fc302704016445b9dce507b928d004f537efa6445e18ea6e18b679411",
          "sha1": "85f02d36e45c41f3607436ce556c77f7e02b2088",
          "md5": "479da45ba8ae4d32050ff8674bcc826d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callisto-1.0.0-dev+mc.1.20.1-sources.jar",
          "url": "callisto-1.0.0-dev+mc.1.20.1-sources.jar",
          "size": 102896,
          "sha512": "afe8b83e53c4a47f1df5c1619ce608378ae783742dd2e7153a09dae42b4bb234b4ffa967fdf97389a1875fe0cbb0ce9cf58370b3848e0d897474896cbbfbafdc",
          "sha256": "81fb9906a8b85957d5db80cb1e55de46ca78501d62f0740f42e4130fe7114071",
          "sha1": "38686f2b1c6a704dff744c4e4159a6c2227b57b7",
          "md5": "cfb91ab8fc0825b13dbba748d66cc287"
        }
      ]
    }
  ]
}
