{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lib",
    "module": "callisto",
    "version": "1.0.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "url": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "size": 33850,
          "sha512": "74cca0b611ca9d50515577d66f318ed16e1a8e2c6602e94c3c9bfd0bc13bedf589b4fe928900166ba5527f2931de0f07eeb937095a3ce172fa49e04281319c31",
          "sha256": "01c47e7c9a0ede9cf35352509cb0f6af9594031755a7e0dd7d767309522543e1",
          "sha1": "6b1edcf1b93dea05129019ea63b5b84a1d10b87b",
          "md5": "a122906fa556addb9e7a3e1a5ed12494"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "url": "callisto-1.0.0-dev+mc.1.20.1.jar",
          "size": 33850,
          "sha512": "74cca0b611ca9d50515577d66f318ed16e1a8e2c6602e94c3c9bfd0bc13bedf589b4fe928900166ba5527f2931de0f07eeb937095a3ce172fa49e04281319c31",
          "sha256": "01c47e7c9a0ede9cf35352509cb0f6af9594031755a7e0dd7d767309522543e1",
          "sha1": "6b1edcf1b93dea05129019ea63b5b84a1d10b87b",
          "md5": "a122906fa556addb9e7a3e1a5ed12494"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callisto-1.0.0-dev+mc.1.20.1-sources.jar",
          "url": "callisto-1.0.0-dev+mc.1.20.1-sources.jar",
          "size": 27829,
          "sha512": "84ead0a4d86c338238110088c8271fea7459998a07efbf5d894f2253cfc188b075ba9a6e13f59db6c503130dc36376e014c3d10539eace7ebac4f3af8a4c3f5a",
          "sha256": "3c21d99352119ec7dab8253f3934d99b176e493c348ad00cc067d4989ca04c6c",
          "sha1": "d9a8def53f8c8e00aba47c280d06d61db6595375",
          "md5": "b2cda4291fe47b663218bfdd2043b032"
        }
      ]
    }
  ]
}
